export const services = [
    "Peinture de maison",
    "Réparation de toit",
    "Jardinage",
    "Plomberie",
    "Électricité",
    "Nettoyage",
    "Menuiserie",
    "Maçonnerie",
    "Décoration intérieure",
    "Décoration extérieure",
    "Cuisine",
    "Climatisation",
    "Chauffage",
    "Aménagement paysager",
    "Déménagement",
    "Informatiques",
    "Traduction",
    "Design graphique",
    "Photographie",
    "Rédaction",
    "Consultation",
    "Juridiques",
    "Financiers",
    "Marketing",
    "Communication",
    "Formation",
    "Coaching",
    "Bien-être",
    "Santé",
    "Beauté",
    "Divertissement",
    "restauration",
    "voyage",
    "transport",
    "réparation automobile",
    "jardinage",
    "garde d'enfants",
    "nettoyage domestique",
    "réparation d'appareils ménagers",
    "tutorat",
    "fitness",
    "garde d'animaux",
    // Ajoutez d'autres services si nécessaire
  ];
  
  export const cities = [
    "Rabat",
    "Fès",
    "Casablanca",
    "Marrakech",
    "Tanger",
    "Agadir",
    "Tétouan",
    "Salé",
    "Kenitra",
    "Oujda",
    "El Jadida",
    "Nador",
    "Béni Mellal",
    "Meknès",
    "Témara",
    "Mohammedia",
    "Khouribga",
    "Errachidia",
    "Taza",
    "Tanger",
    "Ouarzazate",
    "Safi",
    "Berrechid",
    "Tiznit",
    "Larache",
    "Dakhla",
    "Tarfaya",
    "Sidi Ifni",
    "Kénitra",
    "Laâyoune",
    "Al Hoceïma",
    "Taourirt",
    "Tinghir",
    "Sefrou",
    "Guelmim",
    "Ouezzane",
    "Dcheira El Jihadia",
    "Berkane",
    "Midelt",
    "Souk El Arbaa",
    "Skhirat",
    "Sidi Slimane",
    "Khemisset",
    "Ouazzane",
    "Bouznika",
    "Tinghir",
    // Ajoutez d'autres villes si nécessaire
  ];
  

