export const services = [
  "Peinture de maison",
  "Réparation de toit",
  "Jardinage",
  "Plomberie",
  "Électricité",
  "Nettoyage",
  "Menuiserie",
  "Maçonnerie",
  "Décoration intérieure",
  "Décoration extérieure",
  "Cuisine",
  "Climatisation",
  "Chauffage",
  "Aménagement paysager",
  "Déménagement",
  "Services informatiques",
  "Services de traduction",
  "Services de design graphique",
  "Services de photographie",
  "Services de rédaction",
  "Services de consultation",
  "Services juridiques",
  "Services financiers",
  "Services de marketing",
  "Services de communication",
  "Services de formation",
  "Services de coaching",
  "Services de bien-être",
  "Services de santé",
  "Services de beauté",
  "Services de divertissement",
  "Services de restauration",
  "Services de voyage",
  "Services de transport",
  "Services de réparation automobile",
  "Services de jardinage",
  "Services de garde d'enfants",
  "Services de nettoyage domestique",
  "Services de réparation d'appareils ménagers",
  "Services de tutorat",
  "Services de fitness",
  "Services de garde d'animaux",
  // Ajoutez d'autres services si nécessaire
];

export const cities = [
  "Rabat",
  "Fès",
  "Casablanca",
  "Marrakech",
  "Tanger",
  "Agadir",
  "Tétouan",
  "Salé",
  "Kenitra",
  "Oujda",
  "El Jadida",
  "Nador",
  "Béni Mellal",
  "Meknès",
  "Témara",
  "Mohammedia",
  "Khouribga",
  "Errachidia",
  "Taza",
  "Tanger",
  "Ouarzazate",
  "Safi",
  "Berrechid",
  "Tiznit",
  "Larache",
  "Dakhla",
  "Tarfaya",
  "Sidi Ifni",
  "Kénitra",
  "Laâyoune",
  "Al Hoceïma",
  "Taourirt",
  "Tinghir",
  "Sefrou",
  "Guelmim",
  "Ouezzane",
  "Dcheira El Jihadia",
  "Berkane",
  "Midelt",
  "Souk El Arbaa",
  "Skhirat",
  "Sidi Slimane",
  "Khemisset",
  "Ouazzane",
  "Bouznika",
  "Tinghir",
  // Ajoutez d'autres villes si nécessaire
];
